# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_fb_matrix <- function(Y, L, N, K, P1, P, Q, forward, backward, gamma, scaling) {
    invisible(.Call(`_proclhmm_compute_fb_matrix`, Y, L, N, K, P1, P, Q, forward, backward, gamma, scaling))
}

seq2llh <- function(Y, P1, P, Q) {
    .Call(`_proclhmm_seq2llh`, Y, P1, P, Q)
}

compute_llh <- function(Y, n, P1, P, Q) {
    .Call(`_proclhmm_compute_llh`, Y, n, P1, P, Q)
}

seq2llh_gr <- function(Y, P1, P, Q) {
    .Call(`_proclhmm_seq2llh_gr`, Y, P1, P, Q)
}

compute_llh_gr <- function(Y, P1, P, Q) {
    .Call(`_proclhmm_compute_llh_gr`, Y, P1, P, Q)
}

compute_PQ_cpp <- function(theta, para_a, para_b, para_alpha, para_beta) {
    .Call(`_proclhmm_compute_PQ_cpp`, theta, para_a, para_b, para_alpha, para_beta)
}

compute_P_cpp <- function(theta, para_a, para_b) {
    .Call(`_proclhmm_compute_P_cpp`, theta, para_a, para_b)
}

compute_Q_cpp <- function(theta, para_alpha, para_beta) {
    .Call(`_proclhmm_compute_Q_cpp`, theta, para_alpha, para_beta)
}

compute_P1_cpp <- function(para_P1) {
    .Call(`_proclhmm_compute_P1_cpp`, para_P1)
}

seq2llh_re_cpp <- function(Y, para_a, para_b, para_alpha, para_beta, para_P1, quad_nodes, quad_weights) {
    .Call(`_proclhmm_seq2llh_re_cpp`, Y, para_a, para_b, para_alpha, para_beta, para_P1, quad_nodes, quad_weights)
}

compute_llh_rehmm <- function(Y, para_a, para_b, para_alpha, para_beta, para_P1, quad_nodes, quad_weights) {
    .Call(`_proclhmm_compute_llh_rehmm`, Y, para_a, para_b, para_alpha, para_beta, para_P1, quad_nodes, quad_weights)
}

seq2llh_gr_rehmm <- function(Y, para_a, para_b, para_alpha, para_beta, para_P1, quad_nodes, quad_weights) {
    .Call(`_proclhmm_seq2llh_gr_rehmm`, Y, para_a, para_b, para_alpha, para_beta, para_P1, quad_nodes, quad_weights)
}

HMM_mle <- function(Y, n, N, K, P1, P, Q, tot, maxit) {
    invisible(.Call(`_proclhmm_HMM_mle`, Y, n, N, K, P1, P, Q, tot, maxit))
}

#' Viterbi algorithm for HMM
#'
#' Find the most likely hidden state sequence of an observed sequence under HMM
#'
#' @param seq An action sequence coded in integers
#' @param P1 initial state probability vector of length \code{K}
#' @param P \code{K} by \code{K} state transition probability matrix
#' @param Q \code{K} by \code{N} state-action (emission) probability matrix
#'
#' @return a hidden state sequence coded in integers
#'
#' @export
find_state_seq <- function(seq, P1, P, Q) {
    .Call(`_proclhmm_find_state_seq`, seq, P1, P, Q)
}

seq2cllh <- function(Y, P1, P, Q) {
    .Call(`_proclhmm_seq2cllh`, Y, P1, P, Q)
}

compute_cllh <- function(Y, n, P1, P, Q) {
    .Call(`_proclhmm_compute_cllh`, Y, n, P1, P, Q)
}

